[package]
name = "example-todo-app-rust-htmx"
version = "1.0.0"
edition = "2024"

[dependencies]

# db
sqlx = { version = "0.8.5", features = ["runtime-async-std", "sqlite", "chrono" ] }

# web framework
rocket = { version = "0.5.1", default-features = false, features = ["secrets", "tls"] }

# templating
rocket_dyn_templates = { version = "0.2.0", features = ["handlebars"] }
serde = { version = "1.0.219", features = ["derive"] }
chrono = { version = "0.4.40", features = ["serde"] }
serde_json = "1.0.140"

# auth
rocket_airlock = "0.4.0"
thiserror = "1.0"
anyhow = "1.0"
bcrypt = "0.15.0"  # For password hashing
