name: syllabus-tracker-dev
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - config/common.env
      - config/dev.env
      - .secrets.env
    volumes:
      - ./:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
      - /app/target
    depends_on:
      - otel-collector
    networks:
      - syllabus-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    env_file:
      - config/common.env
      - config/dev.env
      - .secrets.env
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - syllabus-net

networks:
  syllabus-net:

volumes:
  cargo-cache:
  target-cache:
  sccache-data:
