{
  description = "Syllabus Tracker NixOS configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";

    # Community flake that packages ngx_otel_module as a NixOS module.
    # Provides services.nginx.otel.*; relies on services.nginx.prependConfig
    # (available from nixos-25.11 onward).
    nginx-otel = {
      url = "github:djvcom/nix-nginx-otel";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Declarative disk partitioning. Used by the `syllabustracker-fresh`
    # output below for nixos-anywhere bootstrap on a freshly-provisioned
    # droplet. The live `syllabustracker-nixos` config still uses
    # ./hardware-configuration.nix, because the existing droplet's
    # cloud-image partition numbering (vda14 before vda1) can't be
    # cleanly described by disko.
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, nginx-otel, disko }:
  let
    commonModules = [
      ./configuration.nix
      nginx-otel.nixosModules.default
    ];
  in {
    # Live config for the existing droplet. Uses hardware-configuration.nix
    # generated by DO's installer at first boot. Deployed by CI via the
    # current workflow.
    nixosConfigurations.syllabustracker-nixos = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = commonModules ++ [
        ./hardware-configuration.nix
      ];
    };

    # Fresh-bootstrap config. Used by nixos-anywhere when provisioning a
    # brand-new droplet (step 9 of the IaC migration). Disko formats the
    # disk to the spec in ./disko.nix and generates fileSystems entries,
    # replacing hardware-configuration.nix. NOT deployed to the live box.
    nixosConfigurations.syllabustracker-fresh = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = commonModules ++ [
        disko.nixosModules.disko
        ./disko.nix
      ];
    };
  };
}
