{
  description = "Syllabus Tracker NixOS configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";

    # Community flake that packages ngx_otel_module as a NixOS module.
    # Provides services.nginx.otel.*; relies on services.nginx.prependConfig
    # (available from nixos-25.11 onward).
    nginx-otel = {
      url = "github:djvcom/nix-nginx-otel";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Declarative disk partitioning. Used by the `syllabustracker-fresh`
    # output below for nixos-anywhere bootstrap on a freshly-provisioned
    # droplet. The live `syllabustracker-nixos` config still uses
    # ./hardware-configuration.nix, because the existing droplet's
    # cloud-image partition numbering (vda14 before vda1) can't be
    # cleanly described by disko.
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Closure-based activation with auto-rollback.
    deploy-rs = {
      url = "github:serokell/deploy-rs";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Runtime secrets decrypted on the host at activation via sops-nix.
    # Host SSH ed25519 key is an age recipient (see .sops.yaml at repo root).
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Treat ../infra/tofu as a non-flake input so the existing
    # infra/tofu/secrets.enc.yaml is the single source of truth for
    # runtime secrets too (no duplication between an infra-side file and
    # a nixos-side file).
    runtime-secrets = {
      url = "path:../infra/tofu";
      flake = false;
    };
  };

  outputs = { self, nixpkgs, nginx-otel, disko, deploy-rs, sops-nix, runtime-secrets }:
  let
    system = "x86_64-linux";
    commonModules = [
      ./configuration.nix
      nginx-otel.nixosModules.default
      sops-nix.nixosModules.sops
      # Make `runtime-secrets` available to configuration.nix via
      # specialArgs / module args.
      ({ ... }: { _module.args.runtimeSecrets = runtime-secrets; })
    ];
  in {
    # Live config for the existing droplet. Uses hardware-configuration.nix
    # generated by DO's installer at first boot. Deployed by CI via
    # deploy-rs.
    nixosConfigurations.syllabustracker-nixos = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hardware-configuration.nix
      ];
    };

    # Fresh-bootstrap config. Used by nixos-anywhere when provisioning a
    # brand-new droplet (step 9 of the IaC migration). Disko formats the
    # disk to the spec in ./disko.nix and generates fileSystems entries,
    # replacing hardware-configuration.nix. NOT deployed to the live box.
    nixosConfigurations.syllabustracker-fresh = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        disko.nixosModules.disko
        ./disko.nix
      ];
    };

    # SSH and activate as root; CI key authorized in configuration.nix.
    # Build in CI (warm /nix/store cache, plenty of RAM) and copy the
    # closure to the droplet.
    deploy = {
      remoteBuild = false;
      nodes.syllabustracker = {
        hostname = "170.64.159.153";
        profiles.system = {
          user = "root";
          sshUser = "root";
          magicRollback = true;
          path = deploy-rs.lib.${system}.activate.nixos
            self.nixosConfigurations.syllabustracker-nixos;
        };
      };
    };

    # Surfaces deploy-rs's schema checks under `nix flake check`.
    checks = builtins.mapAttrs (_: lib: lib.deployChecks self.deploy) deploy-rs.lib;
  };
}
