{
  description = "Syllabus Tracker NixOS configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";

    # Community flake that packages ngx_otel_module as a NixOS module.
    # Provides services.nginx.otel.*; relies on services.nginx.prependConfig
    # (available from nixos-25.11 onward).
    nginx-otel = {
      url = "github:djvcom/nix-nginx-otel";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Declarative disk partitioning. Used by the `syllabustracker-fresh`
    # output below for nixos-anywhere bootstrap on a freshly-provisioned
    # droplet. The live `syllabustracker-nixos` config still uses
    # ./hardware-configuration.nix, because the existing droplet's
    # cloud-image partition numbering (vda14 before vda1) can't be
    # cleanly described by disko.
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Closure-based activation with auto-rollback. Replaces the
    # CI workflow's hand-rolled ssh + rsync + sudo + nixos-rebuild dance.
    deploy-rs = {
      url = "github:serokell/deploy-rs";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, nginx-otel, disko, deploy-rs }:
  let
    system = "x86_64-linux";
    commonModules = [
      ./configuration.nix
      nginx-otel.nixosModules.default
    ];
  in {
    # Live config for the existing droplet. Uses hardware-configuration.nix
    # generated by DO's installer at first boot. Deployed by CI via
    # deploy-rs.
    nixosConfigurations.syllabustracker-nixos = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hardware-configuration.nix
      ];
    };

    # Fresh-bootstrap config. Used by nixos-anywhere when provisioning a
    # brand-new droplet (step 9 of the IaC migration). Disko formats the
    # disk to the spec in ./disko.nix and generates fileSystems entries,
    # replacing hardware-configuration.nix. NOT deployed to the live box.
    nixosConfigurations.syllabustracker-fresh = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        disko.nixosModules.disko
        ./disko.nix
      ];
    };

    # deploy-rs target. Invoked as `nix run github:serokell/deploy-rs -- ./nixos#syllabustracker`
    # from CI or `deploy .#syllabustracker` from a shell inside this dir
    # with deploy-rs in PATH. Activation runs as root via syllabusadmin's
    # NOPASSWD sudo (narrow /nix/store/*/activate + switch-to-configuration
    # rules in configuration.nix). magicRollback auto-reverts if
    # reachability can't be confirmed after activation.
    #
    # remoteBuild = true ships the flake source to the target and builds
    # the closure there, so CI runners don't need nix-derivation infra
    # (just the `nix` CLI to invoke deploy-rs).
    deploy = {
      remoteBuild = true;
      nodes.syllabustracker = {
        hostname = "170.64.159.153";
        profiles.system = {
          user = "root";
          sshUser = "syllabusadmin";
          magicRollback = true;
          path = deploy-rs.lib.${system}.activate.nixos
            self.nixosConfigurations.syllabustracker-nixos;
        };
      };
    };

    # Surfaces deploy-rs's schema checks under `nix flake check`.
    checks = builtins.mapAttrs (_: lib: lib.deployChecks self.deploy) deploy-rs.lib;
  };
}
