name: Deploy to Production

on:
  push:
    branches: [ main ]  # Adjust to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build release
      run: cargo build --release --features production
      env:
        ROCKET_SECRET_KEY: ${{ secrets.ROCKET_SECRET_KEY }}
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      
    - name: Prepare for deployment
      run: |
        # Create deployment directory structure if it doesn't exist
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /var/www/syllabus-tracker/target/release"
        
    - name: Transfer binary to server
      run: |
        # Transfer the binary directly
        scp target/release/syllabus-tracker ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/syllabus-tracker/target/release/

    - name: Transfer template files
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /var/www/syllabus-tracker/templates"
        scp -r templates/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/syllabus-tracker/templates/
        
    - name: Configure and restart service
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Set executable permissions
          chmod +x /var/www/syllabus-tracker/target/release/syllabus-tracker
          
          # Restart the service using our wrapper
          sudo /usr/local/bin/deploy-restart-service
          
          # Check service status
          systemctl status syllabus-tracker.service --no-pager
        EOF
