name: Build and Deploy to Production
on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: honeycombio/gha-buildevents@v2
      with: 
        apikey: ${{ secrets.HONEYCOMB_API_KEY }}
        dataset: syllabus-tracker-build-events
        status: ${{ job.status }}
        
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,format=short
          type=ref,event=branch
          latest
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Set up SSH
      run: |
        STEP_ID=set_up_ssh
        STEP_START=$(date +%s)
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
        
    - name: Transfer files to server
      run: |
        STEP_ID=transfer_files
        STEP_START=$(date +%s)
        
        # Create deployment directory if it doesn't exist
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p ~/syllabus-tracker"
        
        # Transfer all necessary files except large directories
        rsync -avz --exclude='target' --exclude='.git' --exclude='node_modules' \
          ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/syllabus-tracker/
        
        buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID

    - name: Generate secrets file
      run: |
        STEP_ID=generate_secrets
        STEP_START=$(date +%s)
        
        # Create .secrets.env file with necessary environment variables
        echo "HONEYCOMB_API_KEY=${{ secrets.HONEYCOMB_API_KEY }}" > .secrets.env
        echo "ROCKET_SECRET_KEY=${{ secrets.ROCKET_SECRET_KEY }}" >> .secrets.env
        
        # Transfer to server
        scp .secrets.env ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/syllabus-tracker/
        
        buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
        
    - name: Set up GitHub Container Registry credentials on server
      run: |
        STEP_ID=setup_registry_creds
        STEP_START=$(date +%s)
        
        # Create or update the GitHub registry credentials on the server
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p ~/.docker"
        
        # Create a JSON config for Docker to authenticate with GHCR
        cat > docker_config.json << EOF
        {
          "auths": {
            "${{ env.REGISTRY }}": {
              "auth": "$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64)"
            }
          }
        }
        EOF
        
        # Transfer to server
        scp docker_config.json ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/.docker/config.json
        
        buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
        
    - name: Deploy with Docker
      run: |
        STEP_ID=deploy_docker
        STEP_START=$(date +%s)
        
        # Get the short commit SHA for image tagging
        COMMIT_SHA=$(git rev-parse --short HEAD)
        FULL_IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${COMMIT_SHA}"
        
        # Use the production docker compose file but with the image from GHCR
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ~/syllabus-tracker && \
          export APP_IMAGE=${FULL_IMAGE_NAME} && \
          docker compose -f docker-compose.prod.yml pull && \
          docker compose -f docker-compose.prod.yml up -d"
        
        # Clean up old images after successful deployment
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker image prune -f"
        
        buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
        
    - name: Create Honeycomb deployment marker
      run: |
        DEPLOY_TIME=$(date +%s)
        GIT_COMMIT_HASH=$(git rev-parse HEAD)
        GIT_COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')
        
        curl -X POST "https://api.honeycomb.io/1/markers/__all__" \
          -H "X-Honeycomb-Team: ${{ secrets.HONEYCOMB_MARKER_KEY }}" \
          -H "Content-Type: application/json" \
          -d "{
            \"message\": \"Deployed commit ${GIT_COMMIT_HASH}\",
            \"type\": \"deploy\",
            \"start_time\": ${DEPLOY_TIME},
            \"url\": \"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\",
            \"metadata\": {
              \"commit_hash\": \"${GIT_COMMIT_HASH}\",
              \"commit_message\": \"${GIT_COMMIT_MESSAGE}\",
              \"github_actor\": \"${{ github.actor }}\",
              \"github_repository\": \"${{ github.repository }}\",
              \"github_ref\": \"${{ github.ref }}\"
            }
          }"
      env:
        HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
