honeycomb_api_key: ENC[AES256_GCM,data:Vd5JWew6fu7hxC/vGjHTYV3Yle2WHHDxASUusOlA3zwXw9/f3/FjeBeS/T6N/P1zs2Z6+mC2ADaDs9xSn7toMw==,iv:P8CDzeSqX6Y9GOOL7ix5wtue7D5Ua0TTfia9Ffjj3qE=,tag:ZDtfo9pUYWm1zVIGHVPN5A==,type:str]
honeycomb_marker_key: ENC[AES256_GCM,data:3Ho2GtXJbqc3pw+nXKAABJGWCNcaPA==,iv:uCo9b+uuw5NAryRXq+tyS0wHr/lYWKbpL8z8q1nYrwM=,tag:krCZoiA2rzHi3cN8jO5Ayw==,type:str]
rocket_secret_key: ENC[AES256_GCM,data:MYO2hJ6BgMxvlT+o6cHCkHJQrEbaoswXLBLH1OaBMqcOsjmvwwME7KJHw6U=,iv:nJqxBXmTUClhmM1Cd1+5OODl3sy0h+dNwTfcpV5cf2Y=,tag:1JSBF+K4E4QIhe5V6xAaIQ==,type:str]
nixos_server_ip: ENC[AES256_GCM,data:+X+XEaxA4n3wMRtuD8o=,iv:xJ1OPwwnZuTYZY7hoy19Kgu5F3rirWq7a3oL+t7RIhY=,tag:TblQ2s3tpc2kuGQz7d7xyg==,type:str] #ENC[AES256_GCM,data:S+TTpr2UyvVYd72OEb773E9dzjZSPxyESzOdTJ1KaSGrNT/zCzMqS/j89wWB,iv:e1dOYGUqC7sUcrvIXrat1En6FRiiioTr8EvPLR2zpCo=,tag:IWEhTv/HRGA+t7JB8lknGw==,type:comment]
nixos_server_user: ENC[AES256_GCM,data:ApAm1D8P0935uslfWg==,iv:q7Ihd4M49FTSs4C/YeiwkHTYQjpwtyRLaN9XuJ+/5i4=,tag:MhTU2Mp4CsZ3e5qeXD52nQ==,type:str]
#ENC[AES256_GCM,data:7Zs2j6cIIieiyW9SPoaEms17Tw==,iv:5A0BpBthfcQveg5HdWarAo1UH35UJOwLgZ7QfhJ8FMQ=,tag:T2R1kmSE3tpW4hZ44hdfcg==,type:comment]
#ENC[AES256_GCM,data:Ng3McHs/YhO2CgPfAABoAnNgXimFpfaJUQOCKtIOdrEt4Lp5BXk=,iv:DpqR6voHEzXMfINS5x+g6/0gFgQGgOapoed90Tp9k48=,tag:8PP/BNXeGukUXVyNN8LThw==,type:comment]
#ENC[AES256_GCM,data:o25MHnl9M9JjLWxadQ==,iv:rlv8IUIzoR0FPP55SVDhLvR2E5BbdBTKBQgutmjvUJs=,tag:jrnPvRvZsUa6lcbByTITtw==,type:comment]
#ENC[AES256_GCM,data:ZrkGQryFL4FdHLeORh5wvWnTJ19+96RW4wSyP/O2vlFLXP7V,iv:YOCzwg+fG4BrxJ06IZUHG8bWKTKKV0Qlmf4PrBw4/Zg=,tag:zpFdlCWSS0vzFs28K1uBug==,type:comment]
cloudflare_r2_access_key_id: ENC[AES256_GCM,data:c9LyMys/RtC5sHO8H+y1cbiVXU87JA39G/gqevz4RFs=,iv:4kKVTX0j/x2uO75A3gLCygExhPmTHdg8U9wLpT33noo=,tag:w2OaM7MWg/Pslj7pYqTgnw==,type:str]
cloudflare_r2_secret_access_key: ENC[AES256_GCM,data:UdjektFRluSfw7gzMu9+ies+A284OZ4P4jm2d30k6Er6wvKpA7C+alwCCDCdfM5R3GLENFQWTD2eVd/Q7Cq+og==,iv:qE9WI6VX01qZ+I9HUNQYpSPe47/A8Mno4xvp7vaqKbs=,tag:IoAWi/qhpF6TLLhO4E1ftg==,type:str]
cloudflare_r2_backups_access_key_id: ENC[AES256_GCM,data:EMj4Ow5xIPkgxZQYfzZ1iJxCIldvH+n3G6MJgPCELuQ=,iv:l2LfaJpecRQjXsO+boUi0+0aoC4U80FzpcOYFEXXCQ8=,tag:mFf1OZza+eQjEdh2sUJkEA==,type:str]
cloudflare_r2_backups_secret_access_key: ENC[AES256_GCM,data:QWyOJ+BvRss/1L77p7mCvKJUHgaIJtNyZOXdtc/tSCsbXyZANAcdMUZ+G5gZuqvgEoFg8y9FZzOiuT6egekJvw==,iv:ePNGHZdNqfg2lB9HwNMU7AKYQxmnNDzmYNVdEyj565I=,tag:3xmtJd79rG4W54OioFXE/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb2hIbnpqWmxwMXcwMDlH
            SWl2SGN6WHVEbjZHQ3JTQm91eFBnRjVYbVNJCk45RUtBRThEQVBDbGhsK3VSTlhy
            WjhvdVBLQ3gzK3hhN3R3Ulo5a1p6cm8KLS0tIElGRFVYUG55RGo1bTFoQjRrbDBP
            N0ZwK1RxTDNLYWVLWjVuc1ZmSDZqaFUKoX9+y7lBB4xGCCeNC75b78voWlvlRdqs
            tdYDUvI7SwfFLoIOUmgnAicYlFbVUKhjfU0T1P8kpH+hEDwbpUzOhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dkmrzjz5zye09w3vdt74kk4q43erjqhau8ce5f0shd9uzuhjwpfqs2ntkm
    lastmodified: "2026-06-06T11:35:40Z"
    mac: ENC[AES256_GCM,data:1vbaxSm1QgI2dM5bmV+aJJrvYOVjOOrN26DIGvKgghG2FgkvrAx1AbrctvJwvBQSWGxYGyOlqfolNWhO0FDUe1Au1oB2BgFwSW6ae8p+bcifkXq3qsOaKytWOEKS3BJMqMcdzbtWh5/UZsXKCNksx9JCHQ30iRbgbV1v4fINSdY=,iv:LQHo20N/VCgkmJlSwGnRlmzojZ1VEvLAmIPPU37Rvr8=,tag:fldtXzQtjV0ZWRMUpeeb0g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
