honeycomb_api_key: ENC[AES256_GCM,data:Vd5JWew6fu7hxC/vGjHTYV3Yle2WHHDxASUusOlA3zwXw9/f3/FjeBeS/T6N/P1zs2Z6+mC2ADaDs9xSn7toMw==,iv:P8CDzeSqX6Y9GOOL7ix5wtue7D5Ua0TTfia9Ffjj3qE=,tag:ZDtfo9pUYWm1zVIGHVPN5A==,type:str]
honeycomb_marker_key: ENC[AES256_GCM,data:3Ho2GtXJbqc3pw+nXKAABJGWCNcaPA==,iv:uCo9b+uuw5NAryRXq+tyS0wHr/lYWKbpL8z8q1nYrwM=,tag:krCZoiA2rzHi3cN8jO5Ayw==,type:str]
rocket_secret_key: ENC[AES256_GCM,data:MYO2hJ6BgMxvlT+o6cHCkHJQrEbaoswXLBLH1OaBMqcOsjmvwwME7KJHw6U=,iv:nJqxBXmTUClhmM1Cd1+5OODl3sy0h+dNwTfcpV5cf2Y=,tag:1JSBF+K4E4QIhe5V6xAaIQ==,type:str]
#ENC[AES256_GCM,data:S+TTpr2UyvVYd72OEb773E9dzjZSPxyESzOdTJ1KaSGrNT/zCzMqS/j89wWB,iv:e1dOYGUqC7sUcrvIXrat1En6FRiiioTr8EvPLR2zpCo=,tag:IWEhTv/HRGA+t7JB8lknGw==,type:comment]
nixos_server_ip: ENC[AES256_GCM,data:+X+XEaxA4n3wMRtuD8o=,iv:xJ1OPwwnZuTYZY7hoy19Kgu5F3rirWq7a3oL+t7RIhY=,tag:TblQ2s3tpc2kuGQz7d7xyg==,type:str]
nixos_server_user: ENC[AES256_GCM,data:ApAm1D8P0935uslfWg==,iv:q7Ihd4M49FTSs4C/YeiwkHTYQjpwtyRLaN9XuJ+/5i4=,tag:MhTU2Mp4CsZ3e5qeXD52nQ==,type:str]
ssh_private_key: ENC[AES256_GCM,data:Ewme3e/k7SzXVJBFSzMA1ut/q4jmGucYHbPlM7u5MVmNu9m/EPWPnc52EzqZgbecVm2UaNQyForjtqtvOnIyIMX9Qcq1dCKBm2QwZUYaHbIWgLog3yrPvhIXmze2QoWByijmlV277eJdFTGGpgBGOLXwVLWGLz7n1f/TauqxU0wHcTV6Wz4kUHvlLQjDQA/sAxpbNc3mBAlUoEHiSlxJ9lPRq2lTJAZtCh32X+OZESv1LuPKIFjcJtKRa/gGi3Fh7W3McMwvnugZJiyybAjbsYr6oqTsXPPDHJRIDYUcRTMFfS5Uv4/4sGj+Fs/4qkopuWUx1FEuKHJl27Pqb7yj015WK/fnug9FY5R2uL4I2i8TTBf+BM2O/V4wdQKSv52F3HF4T33hDgTjhjmuPXEAQqsbfEt88B3Tblr59pFDj3yMOM7fNshqOCdF6EbvhkAbAYtAmc8NWl4Hc6RxpT7/2r7AzC+l0EIrhn0VaAgDI/s38OhvvbYaiFsp7yH70H0gbewUDlDay3iVx/kjf9aN0j85inZdaGRD60FlwMxJeenY2Ik=,iv:cWa5SywaopX7kNtgURPkadJcI2ClTMAaDQ37Ya2Jz1k=,tag:jAzMBR+UYDCjATDRw9NbdQ==,type:str]
r2_videos_access_key_id: ENC[AES256_GCM,data:bmq39qfPPumt14vSDtciAhpOaMDBqEiG4AvURfp6jSI=,iv:3REhhw6bs/Ksl7L+tcij1K8b/hnh72f1/sw4Fwgebz0=,tag:z5a3EBPIr3vI9IUZQ6jt6A==,type:str]
r2_videos_secret_access_key: ENC[AES256_GCM,data:Z0j+kTtHQqrKbGy24AaRDJ2hd//yQl5UBE316DrlVG3p6syS2JlcKdXCvAp1twrhKiL+H5iawIv8w+FHiv8OMw==,iv:AtHG2JW3z1PxhlFCLy+vR+1jEL9onnCghk6TnAFphZs=,tag:Fh85RAOuDEycElKBGH6fqw==,type:str]
r2_backups_access_key_id: ENC[AES256_GCM,data:lPpQs8CFOgRAk8P5hkPJe9Vcyy914mT4AOCu6WKr/4Y=,iv:0J3AH2HJb24SwybCkTdiGtryEJK3it0VFhyqwFSIYBY=,tag:Hr9ajbRTrQfDdYgjD9vHhw==,type:str]
r2_backups_secret_access_key: ENC[AES256_GCM,data:ryCaYX0YieE8jl+UzXgse/ZN7/0v/KbFHJgHdoRPf51pC+eFaJWNDvPO34eLjs5acqR1I1kRwbflAUyjA7WZlQ==,iv:Xijkr9mib+ZU2NyWqXcQJnKCM504VgBvOIKCGouhKN4=,tag:8qVArJr/jpsu4Fhrp43K9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcEJycXFrQmsyZ0ZBc09N
            NEplVk1EYVk1Tk5NYWtKSXJXWFI0emNPVEEwCmc2VnpabUhKUzZuaHcycHliZHlC
            QWhLa0hHbXFqVWM4Ykh6bldvdjNrWE0KLS0tIDF3bHl0SnR2Tk1UT256MzBZNDNl
            eUJIKzB3SmJPcmhSVzJKOHBvbzR2dUkKlS0PSWlc9g3LX2nYAVEjqfwaUBnT90G0
            CGCqvEfYmds2SpvxCZsKfGmvBPTxB19DjmPAsukFcjWo8WTs0Gaexw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dkmrzjz5zye09w3vdt74kk4q43erjqhau8ce5f0shd9uzuhjwpfqs2ntkm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybzhDVVhRN0RhYkQ3SDlV
            RG9YNEFSMmp3aElEU3ZtOVNtL2Qva1A4S3kwCmpLV2pKRXlvTXM3OTJyZjk0MHVM
            T1JYcFN5UVM4WnZVRUZLSlRzR092TDgKLS0tIDJFMW81YWxDUXpmTExBamNLeU9w
            UnEwclpwVVpIM0JIenFiN3FvNTdhMTgKygWcHs1AbjVZyOLom/fLRnfENmas0Jay
            amTGsalKF69rG1LFMkqHsaqjmr9MJkDTSCNXWCDqRwOnLAgqDSUWqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhxka2zhzu4ynjxfq9cqqs3yv4f4k0sts5cc3tvknmzkq3x49dnshglgxv
    lastmodified: "2026-06-06T11:51:11Z"
    mac: ENC[AES256_GCM,data:SIhNqZ5GwYdokMwM6kYwC+ISU87kXVU3QpybvZ/zgTke41sLmR/TWz0Z5B7whk547yrD/Xh3p8tK8x5lWkBfphnXZ8nr9FeSo/uI0ZC4i7D9N9ADH9oa32FMAe/zL+JlLoj4FvkFn0vLpnvM6hVEppkHq2ji+eZSPHbyGxYsG7w=,iv:4WlDeGzlhls97EQKJNFqrBa+BKxrtCm0XgqYO7jc2jM=,tag:NCg4QV3sGHuRVfZOEyJFpA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
